name: API CI
on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build & Test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.x"
      - name: Test
        env:
          TANGO_PLATFORM_KEY: ${{ secrets.TANGO_PLATFORM_KEY }}
        run: dotnet test

  publish-nuget:
    runs-on: ubuntu-latest
    name: Nuget Publish
    needs: [test]
    # tag a release as v1.0.0....
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.x"
      - name: Install dependencies
        run: dotnet restore

      - name: Extract tag version
        shell: pwsh
        run: |
          $env:GITHUB_REF -match "^refs/tags/v(.+)"
          $versionTag = $Matches[1]
          Write-Host "::set-env name=VERSION_TAG::$versionTag"

      - name: Pack
        run: dotnet pack Raas.Standard --configuration Release -p:PackageVersion=$VERSION_TAG -p:IncludeSymbols=true --output artifacts

      - name: Publish
        env:
          NUGET_SOURCE:  ${{ secrets.NUGET_SOURCE }}
          NUGET_SYMBOL_SOURCE: ${{ secrets.NUGET_SYMBOL_SOURCE }}
          NUGET_ACCESS_TOKEN: ${{ secrets.NUGET_ACCESS_TOKEN }}
        run: |
          dotnet nuget push artifacts/*.nupkg \
            --api-key $NUGET_ACCESS_TOKEN \
            --source $NUGET_SOURCE \
            --symbol-source $NUGET_SYMBOL_SOURCE \
            --symbol-api-key $NUGET_ACCESS_TOKEN
